### ISSUE TITLE
[enhacement] add option to ember generate ember-cli-yuidoc

### ISSUE THREAD

**Issue by vire** [cibernox/ember-cli-yuidoc#10]
Hi, recently I've isntalled/visited several ember-cli addon projects and the standard way how to install them and generate is:

`ember install:addon ember-cli-<addon-name>`

then to generate the necessary files

`ember generate ember-cli-<addon-name>`

so it might be considerable to add this option to this project too, in case somebody would ember-cli provisioning recipes.

What's your opinion?

**Comment by cibernox** [comment]
Good idea. Done.

In version `0.5.2` (released a moment ago) you have this behaviour.

**Comment by vire** [comment]
Thank you!
