### ISSUE TITLE
Fails without internet connection.

### ISSUE THREAD

**Issue by rwjblue** [cibernox/ember-cli-yuidoc#15]
The following error is thrown if no network connection is present when running an unrelated command:

```
% ember s
Future versions of Ember CLI will not support v0.10.33. Please update to Node 0.12 or io.js.
version: 0.2.0
error: --------------------------------------------------------------------------
error: An uncaught YUIDoc error has occurred, stack trace given below
error: --------------------------------------------------------------------------
error:
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
error: --------------------------------------------------------------------------
error: Node.js version: v0.10.33
error: YUI version: 3.18.1
error: YUIDoc version: 0.5.0
error: Please file all tickets here: http://github.com/yui/yuidoc/issues
error: --------------------------------------------------------------------------
```

----

Most likely this is coming from within YUIDoc itself, and the quick fix for non-yuidoc commands is to put the requires inside of the command's `run` function (instead of always requiring `yuidocjs` for any command invocation).

This would mean moving https://github.com/cibernox/ember-cli-yuidoc/blob/master/lib/commands/ember-cli-yuidoc.js#L3-L5 into the `run` function of the command...

**Comment by cibernox** [comment]
Thanks for pointing the solution! I don't have a single second off lately.

I've published `0.6.1`. I hope this was the root of the problem
