### ISSUE TITLE
Get version from package.json

### ISSUE THREAD

**Issue by chriseldredge** [cibernox/ember-cli-yuidoc#16]
It would be nice if the version could be pulled from package.json instead of having to specify it in yuidoc.json.

For compatibility, the addon could look for a version defined in yuidoc.json first, and if it is undefined then get the version from package.json.

**Comment by cibernox** [comment]
Try the newly released 0.6.2 version. I think you will like the new behaviour.

It uses the version in your package.json + the sha of the current commit.
If it's not defined, it will use the name of you current branch + sha. P.e `develop.a1b2c3d4`

**Comment by cibernox** [comment]
Please close this issue if the new behaviour satisfy your needs.

**Comment by chriseldredge** [comment]
That does the trick. Thanks!
